name: resto
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

isar_version: &isar_version ^3.1.0+1
dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  web_socket_channel: ^2.4.0
  flutter_animate: ^4.2.0+1
  floating_bottom_navigation_bar: ^1.5.2
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  socket_io_client: ^2.0.3+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  dio: ^5.3.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  flex_color_scheme: ^7.2.0
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies: 
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/